src/lib/prisma.ts

My Discord username is luka#0010, and I recently joined the Discord channel after watching the video on YouTube. I wanted to share a suggestion regarding the instantiation of the Prisma client.
Based on the best practices outlined in the Prisma documentation, current method of instantiating the PrismaClient using the app directory could potentially lead to some issues. To ensure a more robust and reliable implementation, I recommend adopting this approach as outlined in official Prisma docs.
You can read more about this in Prisma documentation: https://www.prisma.io/docs/guides/other/troubleshooting-orm/help-articles/nextjs-prisma-client-dev-practices

instantiating PrismaClient

---

README.md

The indentation for the command `npm run dev` was inconsistent. This commit removes the indentation to align it with the formatting of the other commands.

Fix inconsistent indentation in README.md

---

src/components/header.tsx

Profile dropdown menu will now close on click.
---
Bug Fix | Dropdown Menu
---
Discord Username: @sudo-adduser-jordan
- Dropdown menu would stay open after navigating to new page.
- Dropdown menu will now close after navigating to a new page.
1. Login.
2. Navigate to dashboard.
3. Navigate to profile.
4. Logout.

Fix: Dropdown Menu

---

README.md
package-lock.json

---
title: Issue # None | This PR is to update the readme to avoid linting warning and utilize MD syntax
---
- Closes #

Updated Readme with 

---

src/app/layout.tsx

---
title: BugFix: Remove spinner in top right when loading pages
---
- [X ] 🐛 Bug Fix
Noticed there's a spinner showing up on the top right corner when pages are loading.
This is part of the NextTopLoader.
Since NextTopLoader includes a loading progress bar, there's no need in an extra spinner, especially when it is misplaced. 
Current state:
After changes: No spinner, only loading progress bar.

bugfix: Remove spinner in top right when loading pages

---

prisma/schema.prisma

---
Bug Fix |
---
Previously  `Result Table: accuracy Column`  would only accept: `9.99`.
Now will accept: `100`, `99.99`.
Also fixes `saveUserResult()` error in `src\app\race\typingCode.tsx`.
1. Login.
2. Navigate to Race Page.
3. Complete a race.
4. View Result Table in Prisma Stuido.
5. Optional: pass test values to `saveUserResult()` or `calculateAccuracy()`.
Convert value once inserting into table. Opposed to converting value to display `100%` at each request.

Fix: Result Table: accuracy Column Validation

---

src/app/(profile-related)/profile/_components/confirmation.tsx
src/app/(profile-related)/profile/page.tsx

---
title: [#102] - fix user account deletion flow
---
Discord Username: @Jo9871
Fixed user account deletion flow, so that it clears session cookies and redirects to the home page.
- Related Issue #102 
- Closes #102 
1. Login / Create account
2. Navigate to [/profile](https://code-racer-eight.vercel.app/profile)
3. Go though the steps to delete account
4. After confirming account deletion, the session is now cleared and you are returned to the homepage

[#102] | fix user account deletion flow

---

src/components/user-dropdown.tsx

---
title: [#106] | update user menu logout colour
---
Discord Username: @Jo9871 
- 🍕 Feature
- 🐛 Bug Fix
- 🚧 Breaking Change
- 📝 Documentation Update
Updated the colour of the logout button text and focus background to red
- Related Issue #106 
- Closes #106 
- 👍 yes
- 🙋 no, because I need help

[#106] chore: update user menu logout colour

---

src/components/mobile-nav.tsx

---
title: No Issue # | missing onOpenChange property
---
missing onOpenChange property on the MobileLink component
- No
- No
- No

Missing onOpenChange property

---

src/app/race/typingCode.tsx

---
Bug Fix  | Race Tab / Click Focus
---
Race input will now:
- auto focus on page load
- be outlined in blue
- tab in and out
- click in and out
1. Navigate to Race Page
2. Tab out
3. Tab in
4. Click out
5. Click in 
6. Resize screen

Fix: Race Tab / Click Focus

---

src/app/race/typingCode.tsx

---
title: Issue #117  | tooltip to show you can press esc
---
Added a tooltip to show users esc button is available to press to reset.
Discord Username: @Buletins
- Closes #
- [x ] 👍 yes

tooltip to show you can press esc

---

src/app/bannerSvg.tsx
src/app/titleBackdropSvg.tsx

There are a lot of errors showing up in the console.
This is due to naming of specific properties, which are expected to be named differently, e.g. stroke-width => strokeWidth.
This change fixes those.
Validate in console there are no more errors.

[BugFix] Fix invalid DOM properties errors in svgs

---

prisma/schema.prisma
src/app/dashboard/recent-races-table.tsx
src/app/race/actions.ts
src/app/race/page.tsx
src/app/race/typingCode.tsx

---
title: Issue #130 | add a column to recent races table on dashboard that takes you to a race with the same snippet 
---
- added a new relation between a Snippet and a Result
- races page first checks searchParams for snippetId, if not found finds a random snippet
- added a new column to recent races table on the dashboard that displays a button to retry the same snippet
- Related Issue #130 
- Closes #130 
- added a new column to recent races table on the dashboard
- no

add a race column to recent races with a button to the same snippet

---

src/components/ui/editable-input.tsx

---
title: Issue #156  | I added a toast for when the user updates the username. 
---
I added a toast for when the user updates the username. It has the title "Username successfully updated.". Description: "Your username has been successfully updated." and a  Variant: "default",
- Related Issue #156 
- Closes #156 
Previously once a user updates their username it gets updated but there was not any form of notification. Now after the introduction of the toast, a toast should pop up when the user successfully updates their name.

added toast for successful name update

---

src/components/ui/editable-input.tsx

---
title: Issue #158  | Toast when updated username is empty string,
---
Added a toast for when the updated username is an empty string. It has a title: "Username cannot be an empty string." Description: "Your username cannot be an empty string." Variant: "destructive",
- Related Issue #158
- Closes #158
Previously once you update the username and put nothing nothing happens. After the introduction of the toast, a red toast should pop up when the user tries to submit an empty string.

Toast empty string update name

---

src/components/ui/editable-input.tsx
src/components/ui/toast.tsx

---
title: Issue #162  | Added check and toast
---
I believe this will provide a better user experience. I added a check to check if newValue === initial value. If it is true a toast will pop up which is using the custom "middle" variant. The toast has title: "Same username as before.", description: "Oops look like your username is same as it was.", and variant: "middle".
- Related Issue #162 
- Closes #162 
To check you can go to profile --> editable input field --> Just click save without changing anything. A blue toast with the title, description as mentioned above should pop up.

Toast for updated name same as initial

---

src/app/add-snippet/page.tsx
src/app/leaderboard/page.tsx
src/components/ui/editable-input.tsx
src/components/ui/heading.tsx
src/components/ui/toast.tsx

---
title: Issue #168  | Added reusable header component.
---
There was an absence of a reusable header component. I added a header component which is located in components --> ui -->  heading.tsx. Because of its absence, the heading in the /leaderboard page and /add-snippet was not consistent. I have also implemented the component on both pages. I did not remove the previous code, I have just commented it.
- Related Issue #168 
- Closes #168 
Leaderboard before: https://imgur.com/aj9p2ad
Leaderboard After: https://imgur.com/gHdBSx6
Snippet Before: https://imgur.com/UfgRkAi
Snipper After: https://imgur.com/CmYK3fI
Going to make adding heading easier anywhere in the application.

Added reusable header component

---

src/app/add-snippet/page.tsx
src/app/layout.tsx
src/app/leaderboard/page.tsx
src/app/page.tsx
src/components/ui/editable-input.tsx
src/components/ui/heading.tsx
src/components/ui/toast.tsx

---
title: Issue #173  | Added classes for consistent layout for the whole application.
---
As mentioned in the bug, "The home page has the following property for the overall layout container and py-24. Leadership page has the following: container md:min-h-[calc(100vh-12rem)] max-w-4xl and the add snippet page has the following: min-h-screen and py-24.
From UI/UX perspective it is better to follow a consistent pattern."
Changes: Added a div to wrap children in the main layout.tsx with the following properties "container h-fit py-2 md:py-24" made the py-24 from the medium screen since home page was not looking good on mobile view with that padding. 
On the main page.tsx removed the class name from the <main>
On page.tsx of leaderboard removed class name from …

Consistent layout

---

src/components/ui/editable-input.tsx

---
title: Issue # 184 | [FEAT]: Cancel name editing on Esc key press
---
Discord Username: @_salyut
I have added profile name editing cancellation on "Escape" key press.
- Related Issue #184 
- Closes #184

#184 Cancel name editing on Escape key press

---

src/app/add-snippet/_components/add-snippet-form.tsx

---
title: Issue #205  | Added link to race route on toast.
---
Now once a user uploads a toast he/she/they can directly go to race page if he/she/they click on the 'Click to Race' button
- Related Issue #205 
- Closes #205 
Before: https://imgur.com/fegFItU
After: https://imgur.com/n8rQrzj
Unsure

added link to race route on toast

---

src/components/ui/button.tsx

---
title: Issue #215 | Added text-slate-800 dark:text-neutral-200
---
Added on outline button variant text-slate-800 dark:text-neutral-200 to fix the issue
- Related Issue #215 
- Closes #215 
add a snippet and the success toast on light mode should have the words "Click to Race" in slate-800
Unsure

Succes toast snippet fixed light mode

---

package-lock.json
package.json
src/app/(profile-related)/profile/page.tsx
src/app/privacy/page.tsx
src/components/add-bio.tsx
src/components/ui/label.tsx
src/components/ui/sub-heading.tsx

---
title: Issue #246 | Added dialog to add bio only front-end
---
Added dialog on the profile page to add a bio. Also added label from shadcn/ui
- Related Issue #246 
- Closes #246 
https://imgur.com/TUTV8io
https://imgur.com/2JdvV0H
Not sure

created the front-end part to add bio

---

src/app/race/race.tsx

---
Issue #322 | Focus race input on first load: Issue
---
Discord Username: @spaghetti#8809
It now focuses on the race input right after user enters the racing page.

[322] bug: focus race input on load

---

src/app/race/race.tsx

---
No Issue # | Move timer to avoid text shifting
---
Discord Username: @xdguido
Playing around with the racer I noticed the timer shifts a lot when time passes. I founded it distracting and leverage that to make my first PR.
The PR involves just a change of position with the Reset button and add an 'item-center' to the container. In the future it could be improved to avoid shifting in the 'seconds' marker. 
I also hide the restart button when it is not racing.
- Closes #

Move timer to avoid text shifting

---

.gitignore
src/app/contributors/_components/github-commit-display.tsx
src/app/contributors/contributor.tsx
src/app/contributors/page.tsx
src/config/site.ts

---
title: Issue #327  | Display each contributor recent commits
---
- Changed cache revalidation from 60s to 1hr to avoid getting rate limited
- Each contributor will display recent 5 commits
- Now user can click on contributor card or their commit and will get directed to corresponding github page
- Fix weekly codes changes not update to latest week
- Add `.vscode` to .gitignore
- Related Issue #327 
- Closes #
https://github.com/webdevcody/code-racer/assets/57098413/95135236-64d7-420e-9aac-acff882f470c

[327] feat: Display each contributor recent commits

---

src/app/contributors/_components/github-commit-display.tsx
src/config/site.ts

---
title: Issue #327 | Quick bug fix: fetch return 401 in GitHubCommitDisplay component
---
Since we didn't have access token yet, fetch will return status 401 bad authorization request
- Related Issue #327
- Closes #

[327] fix: fetch return 401 in GitHubCommitDisplay component

---

package-lock.json
package.json

---
title: Issue # | Add ts-node as package dependency
---
Discord Username: @connnnnnnorl
Looks like `ts-node` was either removed accidentally or never added as a package dependency and was being implicitly required as a globally installed npm package.

fix: Add ts-node as a dependency

---

src/app/leaderboard/users-table.tsx
src/app/users/(user-profile)/(components)/actions.ts
src/app/users/(user-profile)/(components)/profile-card.tsx

---
#442 | [BUG]: Link to user profile on leaderboard not updated & biography cannot be empty
---
Discord Username: @aaronragudos
- [x ] 🐛 Bug Fix
A mistake was made by me so a bug occured in the if statement of the action, updateUserProfile, since it said that if (input.biography) exists, that is when we should only update the biography, however, that condition is returned as false if the biography becomes an empty string, so I fixed it. That conditional was there to prevent us to update the biography even though it's not provided as a parameter.
Next bug was that the href in a table row in leaderboard page was not updated to /users/${user.id}, so I updated them.
- Related Issue #442
- Closes #442 
Video is in issue #442 
- [x ] 🙅 no, because they aren't needed

#442 | [BUG]: Link to user profile on leaderboard not updated & biography cannot be empty

---

src/components/footer.tsx
src/components/mobile-nav.tsx

---
title: No Issue # | fix mobile nav active item text color on light theme, extra space in footer
---
- Closes #

fix mobile nav active item text color on light theme, extra space in footer

---

packages/app/cypress/e2e/src/app/leaderboard/page.cy.ts
packages/app/src/app/leaderboard/loaders.ts
packages/app/src/app/leaderboard/page.tsx
packages/app/src/app/leaderboard/user-rankings.tsx

---
[475]: Display Current User's Overall Rankings on Leaderboard Page
---
Display to the current user their ranking based upon average cpm, average accuracy, and total races played on leader board page.
Discord Username: @stevanfreeborn
+ add `getAllUsersWithResults` method to `loaders.ts` to get all
users with their results from the database
+ add call to `getAllUsersWithResults` method in leaderboard page
+ add call to `getCurrentUser` method in leaderboard page
+ add `user-rankings.tsx` component to display the current users
rankings based upon average cpm, average accuracy, and total
games played
+ added logic to deal with players having same rank and reflecting
that by appending `T-` to rank
+ display rank in ordinal format
+ add test to verify ranking doesn't display if user is not …

[475]: Display Current User's Overall Rankings on Leaderboard Page

---

packages/app/src/app/race/_components/race/race-multiplayer.tsx

---
Issue # 521 Removed an if statement that prevented the socket from being recreated.
---
Discord Username: @motivation
When the user leaves the multiplayer component in any way the socket gets disconnected but not removed. So when we re- enter the page, the socket isn't recreated nor reconnected.
We could possibly refactor this in the future so that we manage the socket's state within the component. For now this change fixes the issue.
- Related Issue #521 
- Closes #521

#521 Fix Multiplayer Start Bug

---

package-lock.json
package.json

Discord Username: @motivation
The npm script to run the server: "PORT=3001 ......" doesn't work on windows. By importing crossenv, both UNIX and Windows developers can run the script.
- Closes #

Add CrossEnv so that Windows based developers can run server

---

packages/app/cypress/e2e/TestPracticeRace.cy.js

---
---
Added wait commands after redirecting to a new page, so cypress will wait until that page fully loads and it will work as expected.
- Closes #

fix cypress test file  

---

packages/app/src/app/race/_components/race/race-practice.tsx

---
title: Issue #548 | Tabs not recognized in practice tests
---
Discord Username: @writeonlycode
Replicated the logic to deal with whitespaces at the beginning of a line in `packages/app/src/app/race/_components/race/race-practice.tsx`, so it can also deal with \t at the beginning of a line.
- Related Issue #548
- Closes #548
1. Run a local instance of the App.
2. Click "Add Snippet"
3. Copy the code below & paste in the snippet to be added, & add the snippet:
```c++
#include <iostream>
int main() {
std::cout << "Hello World!";
return 0;
}
```
The code above has tab characters in it, so the snippet will be added with tab characters to the database.
4. Click "Race", select "C++" and run. You should see the new code snippet. If not, refresh until you got the correct snippet.
5. Before, …

#548 Tabs not recognized in practice tests

---

packages/app/src/app/race/_components/race/race-practice.tsx

---
title: Issue #NONE | [FIX]: add missing parentheses to preventDefault
---
Discord Username: @moaqz
The `ctrl + r` key combination wasn't working as expected because of missing parentheses on the e.preventDefault function.
- Closes #

fix: add missing parentheses to preventDefault

---

packages/app/src/config/prettier-plugin.d.ts
packages/app/src/config/site.ts

---
---
Another attempt at resolving module not found error on prod.
Since `prettier` module has explicitly imported by our codebase, and it's working fine, I'm thinking of explicitly import all prettier plugin module to force nextjs to resolve this module in build phase. This could potentially fix the problem.
- Closes #

Another potential fix for prettier plugin module not found problem

---

packages/app/src/app/leaderboard/users-table.tsx

---
title: Issue #664 Removed top language field sort
---
Discord Username: @.d_k5g_1am_go.
- [✅] 🐛 Bug Fix
Removed top languages field sort for leader board
- Related Issue #664 
- Closes #664
- [✅] 🙅 no, because they aren't needed

#664 top language field sort

---

README.md

---
title: Issue # | Fix Contributor badge in ReadMe
---
Discord Username: @ vignesh-gupta
- Closes #

Minor Fix: Contributor badge in Readme

---

packages/app/src/app/result/replay-timestamps.tsx

---
title: Hide play/pause control when replay is finished
---
Only minor change, when code replay is finished, play/pause control should be removed since it does not do anything. When you click reset control, then play/pause control is available again. Also `useEffect` that handles next timestamp is little bit refactored. It should be easier to read.

Hide play/pause control when replay is finished

---

packages/app/src/app/terms/page.tsx

---
title: Issue #735 |
---
fixed the terms page to view terms as it wasn't viewing any terms previously 
Discord Username: @2dudu
- [Y ] 🐛 Bug Fix
fixed the terms page to view terms as it wasn't viewing any terms to because of an unclosed react fragment i also had to remove all quotation marks because it caused a react-unescaped error when testing , also the date wasn't added so i removed it until i receive any further updates 
- Closes #
previously :
now:
- [Y ] 🙅 no, because they aren't needed

fixed the terms page as it wasn't viewing anything

---

packages/app/src/app/dashboard/_components/recentRaces.tsx

---
title: Issue #729 Achievement notifications are broken
---
Discord Username: @smit309
1. Change in Name Cell Rendering:
Original:
return <span>{snippet.name ?? "-"}</span>
Modified:
return <span>{snippet?.name ?? "-"}</span>;
Description: Introduced optional chaining (?.) to ensure that the name property is accessed only if snippet is defined.
2. Change in Language Cell Rendering:
Original:
const language = snippetLanguages.find((language) => {
if (language.value === snippet.language) {
return language.label;
}
});
return language?.label;
Modified:
const language = snippet?.language
? snippetLanguages.find((lang) => lang.value === snippet.language)?.label
: null;
return <span>{language ?? "-"}</span>;
Description: Refactored the language lookup to use optional chaining and nullish …

issue #729 Achievement notifications are broken

---

packages/app/src/app/dashboard/_components/recentRaces.tsx

---
---
Merged in a change to recent races and it had conflicts with another PR after resolving conflicts there were new typescript errors that needed to be fixed.
- Closes #

Resolve ts errors with merged code, and updated name of variables
