README.md

I have updated the README to describe the project and what technologies we are using, as well as basic setup instrucitons. In addition, I have added a link to CONTRIBUTION.ND

Issue #5 | adds relevant information to readme

---

.env
README.md

add discord url at the bottom of readme.md

add discord url on readme

---

.gitignore

Added .env to gitignore #31

---

CONTRIBUTING.md

#4 I have created a CONTRIBUTING.md file as a reference for other contributors as per rules set by @webdevcody

#4 - CONTRIBUTING.md file created

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/ISSUE_TEMPLATE/task.yml
.github/pull_request_template.md

I added a pull request template as well as 3 issue templates (bug report, feature request and task)
- Related Issue #26 
- Closes #
n/a
n/a
no

#26 | Added pull request and issue templates

---

.env.example
next.config.js
src/app/api/auth/[...nextauth]/route.ts
src/app/page.tsx
src/components/ui/buttons.tsx

@discord: itstman
added login functionality and display user image based on session

#6 Login Capabilities

---

.env.example
docker-compose.yml
package-lock.json
package.json
prisma/schema.prisma
src/app/api/auth/[...nextauth]/route.ts
src/app/page.tsx
src/lib/getSession.ts
src/lib/prisma.ts

---
title: Issue #6 - working on connecting next-auth with Prisma
---
This PR adds the configuration needed to hook up next-auth with the prisma database.  When users are first created for the first time, the prisma adapter will create rows inside both our User and Account tables.  This PR will require a database migration (please run `npx prisma db push`).
- Related Issue #6
- Closes #6
yes, a database migration

Issue #6 - working on connecting next-auth with Prisma

---

src/components/typing/displayedCode.tsx
src/components/typing/typingCode.tsx

---
title: Issue #7 
---
i added a type racer.
note that this pull request focuses on implementing the logic and functionality. the design aspect will be addressed later.

#7 | feat: add type racer

---

package-lock.json
package.json
src/app/layout.tsx
src/components/footer.tsx
src/components/header.tsx
src/components/icons.tsx
src/components/mode-toggle.tsx
src/components/theme-provider.tsx
src/components/typing/displayedCode.tsx
src/components/typing/typingCode.tsx
src/components/ui/dropdown-menu.tsx
src/components/ui/input.tsx

---
title: Issue #55 
---
needed dependencies: lucide-react, next-themes, shadcn's dropdown-menu, input
- Closes #
run npm i

#55 Theme toggle

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/ISSUE_TEMPLATE/task.yml

---
title: Issue #49 | Add prerequisites checklist to issue templates.
---
- [x ] 📝 Documentation Update
Add prerequisites checklist to issue templates. 
The purpose is to minimize repeating issues that have already been created or resolved.
- [x ] 🙅 no, because they aren't needed

Add: Prerequisites Checklist

---

.github/actions/ci-setup/action.yml
.github/workflows/pull-request.yml
package.json

chore: pull request github action

---

package-lock.json
package.json
src/app/leaderboard/page.tsx
src/components/header.tsx
src/components/ui/hover-card.tsx

---
title: Issue # 24
---
Issue #24 | add leaderboard page
- Added LeaderBoardPage
- TopUsers
- FastestUsers
- Responsive
I did not add connection to db. Static data is used.
- Closes #
Video [Link](https://github.com/webdevcody/code-racer/assets/95468529/e9e41a4c-2168-4f7a-9576-cbf7e8443c6c)
It is responsive.
- [ x] 🙋 no, because I need help

[24] feat: add leaderboard page

---

.env.example
src/middleware.ts

---
title: Issue #50 
---
Added middleware to protect routes, in this PR I have just added the dashboard route. 
- Related Issue #50 
- Closes #
I am not experienced with tests.

added middleware dashboard protected

---

src/app/race/displayedCode.tsx
src/app/race/page.tsx
src/app/race/typingCode.tsx

---
title: Issue #7
---
Discord Username: @belm0069
this pr removes the input element, enabling automatic focus when the page loads. Users can now immediately start writing code or click on the code to start writing. this enhancement improves the user experience.
note: that the styling improvements will be implemented in a future update
- Related Issue #7
https://github.com/webdevcody/code-racer/assets/51862296/9c830e17-882c-4e8d-9670-2fa95d6768ee

[7] refactor: type racer

---

src/app/dashboard/page.tsx
src/app/race/typingCode.tsx
src/components/data-table.tsx
src/components/results-table.tsx

---
---
-[ ] 🧑‍💻 Code Refactor
made the table reusable, so we can make use of it in our dashboard in the future
- Related Issue #29 , #84 
- Closes #

Table reusebility

---

package-lock.json
src/app/(profile-related)/profile/_components/confirmation.tsx
src/app/(profile-related)/profile/actions.ts
src/components/icons.tsx

---
title: Issue #102 
---
- Closes #

102 Sign out fix

---

src/components/icons.tsx
src/components/ui/buttons.tsx

---
title: Issue [#111] | update login button
---
Discord Username: @Jo9871 
- 🍕 Feature
- 🐛 Bug Fix
- 🚧 Breaking Change
- 📝 Documentation Update
- Make login button login directly with GitHub instead of redirecting to a login page first
- Update button style to look neater
- Add GitHub Logo to indicate it will log in with GitHub
- Related Issue #111 
- Closes #111 
**Normal State**
**Hover State**
- 👍 yes
- 🙋 no, because I need help

[#111] chore: update login button

---

src/components/user-dropdown.tsx

---
Bug Fix | Dropdown Menu
---
Discord Username: @sudo-adduser-jordan
🚩 Reopened, overwritten by another pull request. 🚩
Profile dropdown menu will now close on click.
- Dropdown menu would stay open after navigating to new page.
- Dropdown menu will now close after navigating to a new page.
1. Login.
2. Navigate to dashboard.
3. Navigate to profile.
4. Logout.

Fix: Dropdown Menu

---

src/app/race/typingCode.tsx

---
Fix | Remove Unnecessary Attribute
---
-Remove unnecessary autoFocus from input
-Remove unnecessary eslint comments

Fix: Remove Unnecessary Attribute

---

src/app/add-snippet/_components/add-snippet-form.tsx
src/app/add-snippet/page.tsx

---
title: Issue #124 |
---
Discord Username: @Psypher1 
Added more languages to the dropdown. Also, extracted the list of languages to an array an mapped over that. This will allow easier addition of more languages
- Related Issue #124 
- Closes #124
none made
nothing really

#124 | fix: add more languages to dropdown

---

src/app/dashboard/accuracy-chart.tsx
src/app/dashboard/cpm-chart.tsx
src/app/dashboard/page.tsx
src/app/dashboard/recent-races-table.tsx
src/lib/utils.ts

---
title: Issue #114 
---
Showing real data on dashboard page
- [*] 🍕 Feature
- [*] 🚧 Breaking Change
- [*] 🧑‍💻 Code Refactor
Getting the real data from page component, passing it down to charts and tables
table with recent races uses server-side pagination and filtering 
- Related Issue #114 
- Closes #114 
On mobile devices tables still are not properly shown. It needs some styling
- [*] 🙅 no, because they aren't needed

#114 dashboard real data

---

package-lock.json
package.json
src/app/layout.tsx
src/app/result/page.tsx

---
title: Issue #97 | Add Social Media Share
---
I have added 2 social media buttons (twitter, facebook). Meta data added.
- react-share
- Closes #
Note: I have changed NEXT_PUBLIC_DOMAIN to https://code-racer-eight.vercel.app.
Video [link](https://github.com/webdevcody/code-racer/assets/95468529/ea00c668-aea6-4e9f-8c28-d8350e4c34bd)
Video 2 https://github.com/webdevcody/code-racer/assets/95468529/706830f4-c7bb-4811-9c60-39f3fdfdbc3a
I have used [ngrok](https://ngrok.com/) to create a virtual link.
> To recreate install the application and sign up. 
> Get the auth token.
> Open the application and run.
```
ngrok http 3000
```

[97] add social media share

---

package-lock.json
package.json
src/app/(profile-related)/profile/_components/confirmation.tsx

---
title: Issue#135 | Cancel button not in modal
---
Discord Username: @Sahad#5043
- [ X] 🐛 Bug Fix
Added the cancel button just below the delete button in confirmation page
- Closes #
I think clicking the CANCEL button to check whether the modal closes or  not will clarify. If you guys have any better alternative then i would love to know.

Added Cancel Button to the confirmation page

---

src/app/(profile-related)/profile/page.tsx

---
title: Issue #143  | I added a margin top of 40px on total points span.
---
It fixes issue #143 since after adding the top margin my name is completely visible. 
- Related Issue #143 
- Closes #143 
Before: https://www.playbook.com/oss-fixed/J8FGEt78QGT9f9RXCWU9xpU8?assetToken=TYzWtUqSxtLaAiAqhiBhJG7s
After: https://www.playbook.com/oss-fixed/J8FGEt78QGT9f9RXCWU9xpU8?assetToken=RA9MnhFCtXDJjAJuXSDudvuY

added margin top 40px on total points span

---

src/components/ui/editable-input.tsx

---
title: Issue #150  | I have it dynamic instead of fixed height.
---
The div had a fixed height of 40px [h-10] I made it h-fit and overflow hidden. 
- Related Issue #150 
- Closes #150

have it dynamic with overflow hidden

---

prisma/schema.prisma
src/app/add-snippet/actions.ts
src/app/api/auth/[...nextauth]/route.ts
src/app/review/actions.tsx
src/app/review/page.tsx
src/app/review/review-buttons.tsx
src/components/icons.tsx
src/components/user-dropdown.tsx
src/types/next-auth.d.ts

---
title: Issue #136 
---
Review page that is accesible only to admins
Discord Username: @scapex76 
- [*] 🍕 Feature
- [*] 🚧 Breaking Change
- [*] 🧑‍💻 Code Refactor
Created a review page, role-based authorization, server actions. 
- Related Issue #136 
- Closes #136 
- [*] 🙅 no, because they aren't needed
prisma db push

#136 review page

---

package-lock.json
package.json
src/app/layout.tsx
src/components/ui/toast.tsx
src/components/ui/toaster.tsx
src/components/ui/use-toast.ts

---
title: Issue #152  | I added Toast from shadcn/ui
---
Added toast component from shadcn ui and added the Toaster component to layout.tsx file
- Related Issue #152 
- Closes #152 
I do not think a test will be needed but I am not sure. Also, I do not know about test.

added toast component from shadc and addedToLayout

---

src/components/ui/editable-input.tsx
src/components/ui/toast.tsx

---
title: Issue #164  | changed position of the div
---
Problem: Due to the position of the div with X and Save button on editable input only 17 characters are visible so any change after the 17th character is not visible since the div is positioned above the input field. For example, with the name "Shreyas Chaliha aka Trace" only till "Shreyas Chaliha ak" is visible. So when I make changes after the 17th character I need to guess and cannot see it in real time.
Solution: Changed these three properties "justify-center w-24 top-0" to "top-11 w-full justify-evenly".
Now real-time changes after the 17th character are also visible.
- Related Issue #164 
- Closes #164 
Before: https://imgur.com/cN4VzK1
After: https://imgur.com/ASFUr3x

Editable input bug fix

---

src/app/race/noSnippet.tsx
src/app/race/page.tsx

---
title: Issue #177  | [FEAT]: Performance Comparison
---
Discord Username: @phoukiethseng
When user navigate to `/race` page, it will be blank if there aren't any existing snippet. So we add a message prompting user to create new snippet first.
- Closes #177 
https://github.com/webdevcody/code-racer/assets/57098413/9bcacd20-b8d2-4189-b30b-6589cc26c1c0

[177] feat: Add prompt message in Race page

---

src/app/add-snippet/page.tsx
src/app/layout.tsx
src/app/leaderboard/page.tsx
src/app/page.tsx
src/app/race/typingCode.tsx
src/components/ui/editable-input.tsx
src/components/ui/heading.tsx
src/components/ui/toast.tsx

---
title: Issue #180 | Disabled paste on input field of Typing code
---
The Bug: I am able copy and paste the same snippet code and able to complete around 2 sec.
My fix: Added onPaste={(e) => e.preventDefault()} on the input. Tried on Chrome and Edge cannot paste anymore.
- Related Issue #180 
- Closes #180 
Steps to recreate: You can just copy and paste the code from the UI.
After adding paste is not working for me anymore.
If someone can try in some different browsers too it will be appreciated.

Disabled paste on typing code input

---

package-lock.json
package.json
src/app/dashboard/PerformanceComparison.tsx
src/app/dashboard/page.tsx
src/components/ui/tabs.tsx

---
title: Issue #133 | [FEAT]: Added Performance Comparison
---
I have added performance comparison chart. 
- Closes #133 
Video [link](https://github.com/webdevcody/code-racer/assets/95468529/07a48e32-516d-459b-b0ee-479a968d30e8)
Image:
None
None

133 added performance comparison chart

---

package-lock.json
package.json
src/app/race/displayedCode.tsx
src/app/race/page.tsx
src/app/race/typingCode.tsx

---
title: Issue #189  | Fixed responsive issue for phone for race page
---
On the race page, the container where we need to type was breaking on the phone. I have added classes to make it responsive. 
- Related Issue #189 
- Closes #189 
Before: https://imgur.com/iymmsfy
After: https://imgur.com/43i2bYQ
After the changes I made it is working fine for me but will require additional test from different phones.
As above will need testing from additional physical phones.

fixed race page responsive issue

---

src/components/header.tsx

---
title: Issue #193 | Just reduced opacity 
---
It might be just my personal preference but I think it looks better with the blur effect.
- Related Issue #193 
- Closes #193 
Before: https://imgur.com/bSyrS69
After: https://imgur.com/pxP1rVq

reduced opacity to add blur effect

---

src/app/add-snippet/actions.ts

---
title: Issue #132 | Added another check if the user has received the achievement previously or not
---
Discord Username: @king_.bradley
Added another check if the user has received the achievement previously or not
- Closes #132

[TASK]: Update: Added check if user has achievement unlocked

---

src/app/dashboard/page.tsx

---
title: Issue #198  | Fixed the overflowing issue and phone-breaking issue
---
- Related Issue #198 
- Closes #198 
Before
Large screen: https://imgur.com/KFwimNN
Phone: https://imgur.com/AjP6L0l
After
Large screen: https://imgur.com/IidndLw
Phone: https://imgur.com/uNymLnE
Should not be anything.
Not sure
New PR since I don't know how to solve the conflict

fixed the styling. 

---

package-lock.json
src/app/race/animation.css
src/app/race/displayedCode.tsx
src/app/race/typingCode.tsx

---
title: Issue #7 
---
Discord Username: @belm0069
i added a blinking cursor to code racer and fix some overflow problems
https://github.com/webdevcody/code-racer/assets/51862296/4c325f83-18af-44cb-8e33-8e625a887541

[7] feat: add blinking cursor to code racer 

---

src/app/add-snippet/_components/add-snippet-form.tsx
src/app/add-snippet/actions.ts

---
title: Issue #146 | [FEAT] Added notifications and form validation
---
I have added error/ success notfications. It also includes empty field validation.
- Related Issue #146 
- Closes #146 #176 
Note: Code is not checked.
Video [link](https://github.com/webdevcody/code-racer/assets/95468529/c854f73f-e1e8-47aa-b4f7-e708bc8d8488)
Images (Update 2):
Error:
Success:
None.

[146] Added form validation and notifications

---

src/app/race/typingCode.tsx

---
title: Issue #201  | fix `line` state in TypingCode component not incrementing properly
---
- Related Issue #201
- Closes #201

[201] fix: `line` state not incremented

---

src/app/race/typingCode.tsx

---
title: Issue #206 |
---
- Related Issue #206 
- Closes #206

206 fix: use template string

---

src/app/add-snippet/_components/add-snippet-form.tsx
src/app/add-snippet/actions.ts

---
title: Issue #126 | Add minimum characters to snippets
---
Discord Username: @Abdullah-Rady 
Enabled the upload button only when the character count (excluding white spaces) is more than 30
- Closes #
- [ x ] 🙋 no, because I need help

Add minimum characters to snippets

---

src/app/race/displayed-code.tsx
src/app/race/typing-code.tsx

---
title: Issue #219  | Cursor is now highlighted on empty line
---
Discord Username: @phoukiethseng
- Related Issue #219
- Closes #219

[219] feat: Cursor is now highlighted on empty line

---

src/app/add-snippet/_components/add-snippet-form.tsx

---
title: Issue #214 | [BUG]: Remove Extra Button 
---
I have removed extra button and resolved display error. I have also resolved error message that pops up after confetti.
- Related Issue #214 
- Closes #214

[214] removed extra button and fixed minor changes

---

src/app/add-snippet/_components/add-snippet-form.tsx

---
title: Issue #214  | Removed unnecessary button.
---
In the "Minimum number of characters is not met" the button was still there.
- Related Issue #214 
- Closes #214 
Try uploading a snippet below 30 characters. The error toast will not have the unnecessary icon anymore.
N/A

removed unnecessary button

---

src/app/add-snippet/_components/add-snippet-form.tsx
src/app/add-snippet/actions.ts

---
title: Issue #221 | [BUG]: Fixed Success/Error message
---
fixed succes and error message when user is not logged in
- Related Issue #221 
- Closes #221

[221] fixed the repetitive bug

---

src/app/add-snippet/_components/language-dropdown.tsx

Discord Username: @belm0069
before: 
https://github.com/webdevcody/code-racer/assets/51862296/b321f446-18a0-41ad-b7a5-2fa04f7c60e6
after: 
https://github.com/webdevcody/code-racer/assets/51862296/31b65321-7803-46a6-b43b-5b8074b36c1d

fix: select Cfamily lang in add your snippet

---

src/app/add-snippet/_components/add-snippet-form.tsx
src/app/add-snippet/_components/language-dropdown.tsx
src/app/add-snippet/actions.ts
src/app/dashboard/performance-comparison.tsx
src/app/leaderboard/page.tsx
src/app/leaderboard/users-table.tsx
src/app/race/actions.ts
src/app/race/animation.css
src/app/race/displayed-code.tsx
src/app/race/multiplayer/[roomId]/page.tsx
src/app/race/multiplayer/page.tsx
src/app/race/page.tsx
src/app/race/practice/page.tsx
src/app/result/voting.tsx
src/context/confetti.tsx
src/env.mjs

---
feat: Multiplayer race pages placeholder 
---
This PR changes the file structure of the `race` page, adds the following sub routes: `/race/practice` `/race/multiplayer` `/race/multiplayer/[roomId]`
These routes have no actual implementation, we need to decide on the multiplayer races architecture. #192 
The current `/race` route was moved to `/race/practice`
The `/race` route now is a selection page for what mode the user wants to play.
- Closes #
New `/race` page looks like this: 
I haven't checked the mobile responsiveness on the `/race` page yet.
- I'm sorry if my commit has a lot of file changes, I ran `prettier -w ./src` to ensure code style, and it changed a lot of things.
- Reviewers, please focus on the `/app/race/` directory …

Race type select page

---

src/app/race/page.tsx

---
Race selection page cards layout & icon fix
---
There was a little mistaken icon included on my last PR, about the race type selection page.
And I was a little annoyed by the text alignment on the right-side card.
current:
updated:

Layout fix on /race page

---

src/app/add-snippet/_components/add-snippet-form.tsx

---
title: How Zod can be implemented to validate.
---
For the add snippet form I have added commented code on how Zod can be implemented.
All the added code are commented out so it should not cause any problems anywhere.

Commented out code with zod implementation.

---

src/app/dashboard/page.tsx
src/app/layout.tsx
src/app/leaderboard/page.tsx
src/app/race/practice/page.tsx
src/app/result/page.tsx
src/components/data-table.tsx
src/components/footer.tsx
src/components/ui/badge.tsx

---
title: Issue #222  | Remove unused btns from result page + unwanted scroll
---
Discord Username: @vigneshgupta 
- Related Issue #222 
- Closes #222 + #230 
Improved the accessibility by removing buttons 
**PREV:**
**UPDATED:**

Remove unused btns from result page

---

src/app/race/page.tsx
src/app/race/practice/page.tsx

---
title: Issue #231  | Randomize Snippets with language options
---
- On `/racer/` page, search params is url to avoid special character conflict (eg. 'c++', 'c#')
- Related Issue #231
- Closes #231

231 random snippet with lang opt

---

src/app/(user)/[userId]/page.tsx

---
title: Issue #241  | Added indivisual user page
---
The whole page was missing Added page. need to work on designing the page next.
- Related Issue #241 
- Closes #241 
Before: https://imgur.com/4jiiutj
After: https://imgur.com/vZGn61q

added userinfo page

---

src/app/race/page.tsx

---
title: Issue #243 | Quick fix URL encoded search params
---
- Related Issue #243 
- Closes #243

[243] fix: url encoded search params

---

src/app/privacy/page.tsx

---
title: Issue #254  | Changed it to upper case with better name.
---
Mistake: The name was starting in lowercase
Correction: Made it uppercase.
- Related Issue #254 
- Closes #

Made it to uppercase with better name

---

src/app/race/page.tsx

---
title: Issue #249 | [BUG]: Fixed mislaingment bug
---
I have fixed the bug reported in the pr.
- Related Issue #249 
- Closes #249 
Bug fix - 
After selecting lang -

[249] race page missarrangement

---

src/app/add-snippet/_components/add-snippet-form.tsx

---
title: Issue #256 | Implemented Zod validation for better error response.
---
Implemented better Zod validation for better user experience and better error messages. 
- Related Issue #256 
- Closes #256 
Error message changes
Both validations failed: https://imgur.com/KCk7dmT
Language Fail: https://imgur.com/ZsOwbNT
Snippet Length Fail: https://imgur.com/x6IwOSh
Not sure

implemented zod validation.

---

src/app/race/no-snippet.tsx
src/app/race/practice/page.tsx

---
title: Issue #261  | Refactor NoSnippet Component
---
- Related Issue #261 
- Closes #261 
https://github.com/webdevcody/code-racer/assets/57098413/43bb9889-0dae-4a9f-9c72-e3e9d9d00ef9

[261] feat: Refactored NoSnippet Component

---

tailwind.config.js

---
Issue #259  | Bug fix for color value
---
Discord Username: @king_.bradley
- Changed color values to fix the bug.
- Closes #

Bug fix for color value

---

src/app/leaderboard/users-table.tsx

---
title: Issue #267  | Fixed the spelling mistake on user-table
---
It was Avarage made it to Average
- Related Issue #267 
- Closes #267

changed from Avarage to Average on table

---

src/app/race/practice/page.tsx

---
Bug fix for getRandomSnippet() function
---
This fix a bug with getRandomSnippet() function on `/src/app/race/practice/page.tsx`
- Related Issue #264
- Closes #264

[#264] Bugfix getRandomSnippet()

---

prisma/schema.prisma
src/app/_actions/result.ts
src/app/leaderboard/page.tsx
src/app/leaderboard/users-table.tsx

---
---
- [*] 🧑‍💻 Code Refactor
- Closes #
prisma db push

fix misspelling from avarage to average

---

src/app/race/no-snippet.tsx
src/app/race/practice/page.tsx
src/components/header.tsx
src/components/mobile-nav.tsx
src/components/user-dropdown.tsx

---
title: Issue # | User Avatar in not showing after sign in mobile navigation bar 
---
User avatar was not showing after sign in mobile navigation 
fixes: 
- fixed: user avatar not showing after sign in 
ed Tickets & Documents
- Closes #

fix: fixed the mobile nav after sign in

---

src/app/race/RaceTracker.tsx

---
title: Issue # | Fix progress bar shot pass 100 percent
---
- Related Issue #282 
- Closes #282

[282] fix: progress bar shot pass 100 percent

---

src/app/race/Race.tsx

---
title: Issue #280 |
---
Discord Username: @batata
- [ x] 🐛 Bug Fix
Firstly the input was being compared in a wrong way to the snippet when it reaches the last character, and if they match, the useEffect (which checks if they match) was in an infinite loop cause the endTime was being changed and was a dependency at the same time, so i put a condition to only change it when its null.
- Related Issue #280 
- Closes #280

#280 | Race not getting stuck anymore and redirecting correctly

---

src/app/(profile-related)/profile/_components/change-name-form.tsx
src/app/dashboard/recent-races-table.tsx
src/app/layout.tsx
src/app/result/first-race-badge.tsx
src/app/result/page.tsx
src/app/result/voting.tsx
src/components/footer.tsx
src/components/icons.tsx
src/components/main-nav.tsx
src/components/ui/heading.tsx
src/config/site.ts

---
title: No Issue # | refactor, result page error case fix
---
- refactor footer, nav, heading, site config, icons
- add nowrap to re-race button, remove raceId column
- handle case where user navigates directly to /result page without finishing a race first
- format unformatted files
- Closes #
- no ui changes
- no

refactor, result page error case fix

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/ISSUE_TEMPLATE/task.yml

---
title: Issue # None | Updated issue creation templates
---
Discord Username: @ vigneshgupta 
While creating issue we cannot check the checkbox. So keeping it check so make sure issue creator know that they are agreeing that they have following the process before issue creations.
- Related Issue # None
- Closes # None

Updated issue templates

---

src/app/add-snippet/_components/add-snippet-form.tsx
src/app/add-snippet/page.tsx
src/app/race/no-snippet.tsx

---
title: Issue # 298 Snippet language base on language set by user at first. 
---
Discord Username: @yuhanna
- [x ] 🍕 Feature
it will select the language based on user selecting at start, of race page
- Related Issue  #298 
- Closes #298

based on language set by user new snippet language is set

---

.env.example

Env example was accidentally removed, readding into project

---

src/app/dashboard/page.tsx
src/app/layout.tsx
src/app/leaderboard/page.tsx
src/app/race/page.tsx
src/components/footer.tsx
src/components/header.tsx
src/components/main-nav.tsx
src/components/mode-toggle.tsx
src/components/ui/button.tsx
src/components/ui/heading.tsx
src/styles/globals.css

---
---
Fixed all conflicts and Added New Layouts and Styles (Style Updated)
- Closes #

Major Design Update: Fixed Styling Issues

---

src/app/result/page.tsx

---
title: Issue #212 | Moved code to fetch user result only if user is available
---
- Closes #

Moved code to fetch user result only if user is available

---

src/app/contributors/page.tsx
src/config/site.ts

Discord Username: @PatalJunior
- [✅ ] 🍕 Feature
Added a contributors page
- [✅ ] 🙅 no, because they aren't needed
Well, I just added a page, that isn't much, but it's something.

Contributors page

---

src/app/add-snippet/_components/add-snippet-form.tsx
src/app/add-snippet/_components/language-dropdown.tsx
src/app/add-snippet/page.tsx

Discord Username: Floky Huan#2876
Refactored the add snippet component. Was it planned to make validation based on which language was selected for the code snippet window?
If that's the case I'm open to any suggestions how to do that...

[176] Add error checks to Add snippet page

---

.env.example
src/app/page.tsx

---
title: Issue #333  | Implemented call to GitHub API to get stars from repo with  revalidate: 60,
---
Implemented call to Git Hub to get stars for the project. This will require Github Access Token.  To get the token https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens
I have updated the .env.example too
- Related Issue #333 
- Closes #333

added github stars on homepage.

---

src/app/leaderboard/page.tsx

---
title: Issue # | [#332](https://github.com/webdevcody/code-racer/issues/332)
---
Discord Username: @industrializeddark
- Related Issue #332 
- Closes #332

332 | Leaderboard should only include users with at least one result

---

src/app/add-snippet/_components/language-dropdown.tsx

---
---
Langage Dropdown Issue Overflow Fixed 
Discord Username: @aweshchoudhary
- Closes #

Language Select Dropdown Overflow issue fixed

---

package.json
prisma/schema.prisma
prisma/seed-data/snippets.ts
prisma/seed.ts

---
title: Issue #302 | Predefined practice snippets
---
Discord Username: @lukedasloth
- [ x  ] 🍕 Feature
Created 1 sample snippet for each language and created the seed script to populate the database when the program starts.
- Related Issue #302

[FEATURE]: Predefined practice snippets #302

---

src/app/race/code.tsx

---
title: Refactoring code erros - practice page
---
I created a function to verify if exists any error and then return the error message on the practice code, just removed the logic from the return and splited on a function.
Accessibility is not impacted here, since there are no visual changes(colors, fonts, sizes...), just a logic.

Refactor: split code erros validation to a function

---

src/app/banner-svg.tsx
src/app/hero-banner.tsx
src/app/layout.tsx
src/app/page.tsx
src/app/title-backdrop-svg.tsx
src/components/main-nav.tsx
src/components/ui/heading.tsx
tailwind.config.js

---
#342 Refactoring home page layout. Adding better responsiveness, new special font, others
---
Discord Username: @skwillzy
I made changes, all primarily on the home page. I made it so that there wasn't so much empty space especially on larger screens and so that the content was centered vertically. I also made the page more responsive to screen sizes.
For the SVG lines, I made them blend in better by having a ::before background gradient and made them take up more of the screen.
I also added a new font that I'm open to changing but it stands out a lot more, it can be accessed in tailwind using font-special.
I updated the wording to be more captivating and changed duplicate h1 tag to a p tag.
- Related Issue #342 
- Closes #342 
I've tested this for various screen sizes. It's fully …

#342 Refactoring home page layout. Adding better responsiveness, new special font, others

---

src/app/contributors/page.tsx
src/config/site.ts

---
title: Updated contributors to fetch from Github API
---

Updates contributors page to pull from API

---

package-lock.json
package.json
src/app/race/Race.tsx
src/app/race/race-timer.tsx

---
title: Issue #300  | feat: New Race Timer
---
- Now no op key won't trigger start timer
- Added new RaceTimer component
- Related Issue #300 
- Closes #300 
- When start typing, timer will start
- Timer will reset when user hit Restart button or press ESC key
https://github.com/webdevcody/code-racer/assets/57098413/492f6dcc-d979-444f-be25-d707b62bd8fb

[300] feat: Race Timer

---

src/app/race/code.tsx

---
Fix race text legibility on dark mode
---
Discord Username: @skwillzy
You weren't able to see the character you were currently on as the text was really light. I made it black so that it's visible while you're typing.
- Related Issue # N/A
- Closes # N/A
Helps visibility

Fix race text legibility on dark mode

---

package-lock.json
package.json
src/app/contributors/contributor.tsx
src/app/contributors/page.tsx
src/app/page.tsx
src/components/ui/avatar.tsx
src/config/site.ts

---
title: Issue #327 | Refactor Contribution Page
---
- Refactored #345
- Added api access token in siteConfig
- Created Contribution component
- Related Issue #327 
- Closes #

[327] refactor: contribution page

---

src/app/contributors/contributor.tsx
src/app/contributors/page.tsx
src/components/ui/avatar.tsx

---
title: Issue #351  | Added new design
---
Discord Username: @trace2798 @phoukiethseng 
Added more clean cards to display contributors. 
- Related Issue #351 
- Closes #351 
Before: 
After: 
Not sure

Added new design for contributor card

---

src/app/page.tsx
src/config/site.ts

---
title: Issue #354  | Refactor GitHub stars code to fit the pattern
---
Discord Username: @phoukiethseng @trace2798 
- Related Issue #354
- Closes #354

[354] refactor: github stars code to fit the pattern

---

src/app/contributors/contributor.tsx

---
title: Issue #358 | Refactor: Contributor avatar fallback now display abbreviated name
---
Discord Username: @phoukiethseng @trace2798 
- Avatar fallback of Contributor component will display contributor abbreviated name
- Related Issue #358
- Closes #358 
- Before:
- After:

[358] Refactor: Contributor avatar fallback now display abbreviated name

---

src/app/(profile-related)/profile/_components/change-name-form.tsx
src/app/(profile-related)/profile/_components/logout-button.tsx
src/app/(profile-related)/profile/_components/profile-nav.tsx
src/app/(profile-related)/profile/page.tsx
src/components/achievement.tsx

---
---
I have redesigned the User Profile Page and Achievements Section
Discord Username: @aweshchoudhary
- Closes #

Redesigned Profile Page And Achievements Section

---

src/app/race/practice/page.tsx

Update the message on the race page when there are no snippets available
---
title: Issue #362 | update no snippet message grammar
---
Discord Username: @Jo9871 
- 🍕 Feature
- 🐛 Bug Fix
- 🚧 Breaking Change
- 📝 Documentation Update
Updated race page error message when no snippet is found.
- Related Issue #362 
- Closes #362 
Before:
After:
- 👍 yes
- 🙋 no, because I need help

[#362] | update no snippet message grammar

---

prisma/seed-data/snippets.ts

---
Issue #370 | Fix typescript language in seed data
---
Discord Username: @FragAverage
Correct usage of word "typescript" as loaded from the query string when loading into a new race for the typescript language.
- Related Issue #370 
- Closes #
None
None

[370] chore: Fix typescript language in seed data

---

src/app/contributors/page.tsx
src/config/site.ts

---
title: Issue #327 | Added weekly code addtions and deletion in Contributors page
---
Discord Username: @phoukiethseng @trace2798 
- Added `siteConfig.api.github.cacheRevalidationInterval` and `siteConfig.api.github.githubWeeklyActivity`
- Contributor page now show current week commit additions and deletions
- Related Issue #327
- Closes #
(pov it's 4AM)

[327] feat: Added weekly code addtions and deletion in Contributors page

---

src/app/hero-banner.tsx

---
title: Hero CTA Poor Contrast 
---
BEFORE (Poor Contrast)
AFTER (Better Contrast and an Arrow)

Hero CTA - Poor contrast fix

---

src/app/race/race.tsx

---
Fix: Issue #373 |
---
-Tab newline will now work as expected
- Closes #373
https://github.com/webdevcody/code-racer/assets/108599131/464dae47-1f42-4216-8ad9-309ca0f4bbfe

Fix: Tab Newline #373 

---

src/app/race/code.tsx
src/app/race/race.tsx

---
title: [390][Task]: Added totalErrors to Code component
---
Discord Username: @102.R.dd_Suti79
Added totalErrors to console.table
- Related Issue # [TASK-390]
- Closes #
Tested locally

[390][Task]: Added totalErrors to Code component

---

src/app/race/race.tsx

---
Feature: Issue #383 |
---
-enabled Ctrl + Arrow
-add logic for feature
- Closes #383 
https://github.com/webdevcody/code-racer/assets/108599131/4d635662-0f83-465a-9170-a4115899d68e

Feature: Ctrl + Arrow

---

src/app/race/race.tsx

---
Fix: Issue #395 |
---
-race will start when input is created
- Closes #395 
https://github.com/webdevcody/code-racer/assets/108599131/bde80e34-1764-4ec2-a313-c4d8469405cc

Fix: Dont start a race on non alphanumeric button click #395

---

src/components/main-nav.tsx
src/components/mobile-nav.tsx
src/lib/utils.ts

---
title: Issue #380 | Active route indicators
---
Discord Username: @flokyhuan
I've added a utils function to take in the current route and item menu route link. I use this on two places thats why I added it to utils. I've tried to use pathname hook inside the util function but pre commit hooks threw an error.
- Closes #

380 active route indicators

---

CONTRIBUTING.md

updating the docs to make it easier to follow

---

src/app/(profile-related)/profile/actions.ts

remove catchError from server action

---

src/app/contributors/_components/additions-deletions.tsx
src/app/contributors/_components/proportion-bar-chart.tsx
src/app/contributors/contributor.tsx
src/app/contributors/page.tsx
src/config/site.ts

---
title: Issue #327 | Added code changes to each contributor
---
Discord Username: @phoukiethseng @trace2798 
- Extensive refactoring in Contributors page
- Renaming some variable, type, interface to avoid ambiguity
- Related Issue #327 
- Closes #
- Before
- After
(POV: You're looking at your own code)

[327] feat: Added code changes to each contributor

---

src/components/ui/use-toast.ts

---
title: Issue # | Bug in server component "use-toast.ts"
---
Discord Username: @102.R.dd_Suti79
Change to client component, and changed the imports.
- Closes #

[399][Bug]-Change to client component, and changed the imports

---

src/app/race/code.tsx
src/app/race/race.tsx

---
Feature: Issue #401 |
---
-Add line numbers
-Highlight current line number
- Related Issue #401
https://github.com/webdevcody/code-racer/assets/108599131/26340834-7927-4238-b11e-0c7dd963536d
A starting point. 
This might not reslove the issue completely. 
I will remove my comment on the issue so others can feel free to work on it.

Feature: Numbered Lines

---

src/app/add-snippet/_components/language-dropdown.tsx
src/app/race/_components/friends-race.tsx
src/app/race/_components/multiplayer-race.tsx
src/app/race/_components/practice-race.tsx
src/components/ui/button.tsx

---
title: Style Changes to Race page Cards
---

Style changes to Race Page Cards

---

src/components/ui/dropdown-menu.tsx

Discord Username: @ergo
Simply added "hover:cursor-pointer" in the className for the drop down menu item component.
- Related Issue #419
- Closes #419

#419 | [BUG]: Missing pointer cursor on hover in dark / light mode dropdown menu as well as profile

---

src/app/dashboard/components/recentRaces.tsx
src/app/dashboard/races/page.tsx
src/app/dashboard/snippets/page.tsx
src/app/leaderboard/page.tsx
src/app/leaderboard/users-table.tsx

---
title: Issue #407  |
---
Fix crashes that caused by search params
- Related Issue #407 
- Closes #407

[#407] Fix: search params crash

---

src/app/result/page.tsx

---
---
Discord Username: @under.ctrl
- Closes #

fix: spelling mistake `implmemented` to `implemented`

---

src/app/(profile-related)/profile/page.tsx
src/app/contributors/page.tsx
src/app/race/_components/friends-race.tsx
src/app/race/_components/multiplayer-race.tsx
src/app/race/_components/practice-race.tsx
src/components/header.tsx

Discord Username: @ergo
The race card buttons looked off because they were not aligned, I used tailwindcss to align it.
- Related Issue #434
- Closes #434

#434 | Aligned race card buttons

---

src/app/result/chart.tsx
src/app/result/page.tsx

---
title: Issue #431 | [BUG]: Fix Improper State in Results 
---
Improper state usage. Conflict with Tooltip's content rendering and main compoent rendering.
Seperated the components and useEffect to set the state variable.
> recharts(github): https://github.com/recharts/recharts/blob/master/src/component/Tooltip.tsx
- Related Issue #431 
- Closes #431 
Before:

[431] fixed improper state usage

---

src/app/race/_components/report-button.tsx
src/app/race/race.tsx

---
#444 | [BUG]: Progress is not reset after reporting a snippet.
---
Discord Username: @aaronragudos
- [ x] 🐛 Bug Fix
- [ x] 🧑‍💻 Code Refactor
Did a little cleaning of the code in race.tsx file, and fixed the bug mentioned in the title.
- Related Issue #444
- Closes #444 
A video of this is uploaded on the issue #444 
- [x ] 🙅 no, because they aren't needed

#444 | [BUG]: Progress is not reset after reporting a snippet.

---

src/components/footer.tsx
src/config/site.ts

---
title: Issue #438 | Add discord link to footer
---
Discord Username: @connnnnnnorl
Add a link to the discord server to make it easier for folks who are new.
- Closes #438 
**Mobile**
**Desktop**

feat: Add discord link to footer

---

package-lock.json
package.json
src/app/add-snippet/_components/actions.ts
src/app/add-snippet/_components/add-snippet-form.tsx
src/app/race/actions.ts
src/app/race/race.tsx
src/app/result/actions.ts
src/app/result/page.tsx
src/app/result/voting.tsx
src/app/review/actions.ts
src/app/review/review-buttons.tsx
src/app/users/(user-profile)/(components)/actions.ts
src/app/users/(user-profile)/[userId]/actions.ts
src/app/users/(user-profile)/[userId]/page.tsx
src/lib/actions.ts
src/lib/utils.ts
src/styles/globals.css

---
---
- [*] 🍕 Feature
- [*] 🧑‍💻 Code Refactor
For now, this wrapper just validates the input. In future, I want to be able to create a context like it was in next-safe-action
- Closes #

Server action wrapper

---

src/app/contributors/_components/counting-animation.tsx
src/app/contributors/_components/github-commit-display.tsx
src/app/contributors/_components/pagination-bar.tsx
src/app/contributors/contributor.tsx
src/app/contributors/page.tsx
src/config/site.ts

---
title: Issue #327  | Added Contributor Counter and Implemented Pagnination
---
- Implemented Pagination to avoid getting rate limited
- Fix bug where api request only return top 30, now it return top 100 which is limit per one request
- Related Issue #327
- Closes #
https://github.com/webdevcody/code-racer/assets/57098413/7ecabfff-0cba-4690-b5f3-086a855f53db
POV: You're trying to stay in GitHub rate limit (it's 60 per hour)

[327] feat: Added Contributor Counter and Implemented Pagnination

---

src/app/race/race.tsx

---
Fix: Issue #437 | Issue #401
---
-Remove Arrow Keys.
-Remove Tab.
-Enter will only create one error.
-Lock typing if there is an error.
-Remove Backspace() function call inside Enter(). (Why someone decieded to put a Backspace function call inside a key that does not backspace I have no idea).
- Closes #437
- Closes #401
https://github.com/webdevcody/code-racer/assets/108599131/5c7c822c-5851-40a6-9f65-04ed88c0f8ed
I went ahead and completed this issue.
I saw it was high priority and this may be extremely confusing for some one unfamiliar with this file.
The arrow and tab keys have also been removed. 
They are not needed if we are decieding to use this functionality descriebed in this issue.
I would also prefer we don't use them …

Fix: Issue #437 | #401

---

src/app/race/(play)/practice/page.tsx
src/app/race/_components/report-button.tsx
src/app/race/race.tsx
src/components/cache-buster.tsx

---
---
Discord Username: @webdevcody
- Closes #

force refresh race page when navigating

---

src/app/add-snippet/_components/language-dropdown.tsx

---
title: Feature # | Add pre-selected language feature
---
Discord Username: @ysl0212
Persist the last selected language and store in local storage
when user come back to select page, it will be pre-selected
- Closes #

Add Pre-Selected Language Feature

---

src/app/result/page.tsx
src/app/result/topten.tsx

---
Feature: Issue #129  
---
-add topten.tsx
-add top ten table for result snippet
-add link to profile
-add dynamic accuracy colors
-remove unused imports
- Closes #129
https://github.com/webdevcody/code-racer/assets/108599131/d5a7d5b9-593a-4bd6-b9ad-964e7e3573b6

Feature: Show Other's top 10 Results for snippet #129

---

src/app/result/chart.tsx
src/app/result/first-race-badge.tsx

---
title: Issue #422 
---
You wont get an error on your result page anymore
- Related Issue #422 
- Closes #422

fix: infinite re-rendering

---

src/app/contributors/_components/counting-animation.tsx
src/app/contributors/page.tsx

---
title: Issue #327 | Improve CountingAnimation performance
---
- Refactor CountingAnimation component limiting update interval to 100ms, therefore improve performance
- Added type to getContributorsActivity's response object (before it was type of `any`)
- Remove or comment out logging
- Related Issue #327
- Closes #

[327] refactor: Improve CountingAnimation performance

---

cypress/e2e/src/app/contributors/page.cy.ts

---
title: Issue #464  | Contributors Page E2E Test
---
- Mainly test navigating in Contributors page
- Related Issue #464 
- Closes #464 
https://github.com/webdevcody/code-racer/assets/57098413/e5c9febe-34d7-4b9e-a4d5-259d1a2f45f4

[464] Contributors Page E2E Test

---

src/app/race/_components/multiplayer-race.tsx
src/components/footer.tsx
src/components/header.tsx
src/components/main-nav.tsx
src/components/user-dropdown.tsx

Discord Username: 
Improved visuals of menu items in Header nav. Changed styling of header and footer.
Before: 
[Screencast from 07-20-2023 06:25:45 PM.webm](https://github.com/webdevcody/code-racer/assets/112876685/cfc5d86a-1a7b-4baa-8503-2be3952a3d0f)
After: 
[Screencast from 07-20-2023 06:24:12 PM.webm](https://github.com/webdevcody/code-racer/assets/112876685/1d44535a-a613-44c7-90e5-2789d30fe35e)
- Related Issue #456 
- Closes #456

#456 | Improved header nav UI and styling for header & footer

---

src/components/footer.tsx
src/components/header.tsx

Before: 
After:
- Related Issue #466 
- Closes #466

#466 Change dark mode header color to main bg color, improve footer text contrast

---

src/app/result/page.tsx

---
Chore: Update /result/page.tsx CSS
---
-rearrange tabs
-add margin to tabs
-add text accent to buttons
-edit / move shortcut badge
-add text color to card title
-remove comments

Chore: Update /result/page.tsx CSS

---

src/app/review/page.tsx

Discord Username: @hawk1682
Replaced code tags with pre and also made additional styling, also fixed heading title now it is centered and fixed "Total characters" count now it is always on the bottom.
- Related Issue # [[FEATURE]: In Review page code tags should be replaced with pre so an admin can review the code with correct indents #468](https://github.com/webdevcody/code-racer/issues/468)
- Closes # [[FEATURE]: In Review page code tags should be replaced with pre so an admin can review the code with correct indents #468](https://github.com/webdevcody/code-racer/issues/468)

#468 Replaced code tags with pre and added additional styling

---

CONTRIBUTING.md
README.md

---
title: Issue # 470
---
Just minor docs clean-up
- Related Issue #470
- Closes #470 
No

#470 Fixed minor docs issues

---

src/app/leaderboard/loaders.ts
src/app/result/loaders.ts

leaderboard
---
---
- Closes #

fix: show only users with >= 5 results on the leaderboard

---

src/app/leaderboard/users-table.tsx

---
title: Issue # | Repeat Word
---
Discord Username: @Blake Lawrence83
removed an unnecessary repeat word
- Closes #

removed repeat word "complete"

---

.env.example

…in contributing.md
---
spelling error and punctuation
---
Discord Username: @BlakeLawrence83
changed "where" to "were" in in .env.example comments section and added a comma in CONTRIBUTING.md to help it read a bit better.
- Closes #

corrected a spelling error within .env.example

---

src/app/race/race.tsx
src/app/result/page.tsx
src/app/result/replay-timestamps.tsx

---
title: Issue #272 
---
- [*] 🍕 Feature
- Related Issue #272
- Closes #272

272 result for anonymous

---

.env.example
src/app/race/_components/practice-race.tsx
src/components/footer.tsx
src/components/ui/button.tsx

---
title: Issue #490  | hover state for practice button
---
- Related Issue #490 
- Closes #490 
no

490 practice button style

---

.env.example
src/env.mjs

---
Make MULTIPLAYER env not fail build when not defined + add it to .env.example
---
This PR makes the environment variable `MULTIPLAYER` not fail your build when not defined in the environment (It will default to false)
Also adds it to .env.example
- Related Issue #481 #484 
- Closes #481 #484

MULTIPLAYER Env not required

---

src/app/result/topten.tsx

TopTen component
---
---
Discord Username: @industrializeddark
- Closes #

Fix: Show only users in top 10 once instead of having repeats of same user

---

src/app/race/(play)/multiplayer/page.tsx
src/app/race/_helpers/race-helpers.ts
src/app/race/race.tsx
src/config/site.ts
src/wss/game.ts

---
title: Issue #479  | Multiplayer Matchmaking
---
Guest user will be only matched against other guest user, same as logged in user
TODO: For logged in user, pick race which best suited to current user (Current implement choose first race of result query)
- Related Issue #479 
- Closes #
https://youtu.be/LdFpRrCix0Q

479 Multiplayer Matchmaking

---

src/app/add-snippet/_components/add-snippet-form.tsx
src/app/users/(user-profile)/(components)/confirmation.tsx
src/components/data-table/data-table-view-options.tsx

---
Fix: Minor CSS Changes
---
-add text-accent
-edit toggle width
-center text

Fix: Minor CSS Changes

---

src/app/race/_components/practice-race.tsx
src/app/race/code.tsx
src/app/race/race.tsx
src/components/ui/button.tsx

---
title: Better Colors for Light and Dark mode
---

Color fixes for Dark / Light mode

---

src/app/users/(user-profile)/(components)/UserCommits.tsx
src/app/users/(user-profile)/[userId]/page.tsx
src/types/github.ts

---
title: User Commits added to Profile 
---

User Commits added to Profile

---

src/app/dashboard/accuracy/page.tsx
src/app/dashboard/cpm/page.tsx
src/app/dashboard/races/page.tsx
src/app/dashboard/snippets/page.tsx

---
title: Issue # |  Word structure and punctuation correction
---
Discord Username: @blakelawrence83
changed the word checkout to check out and removed 2x full stops to keep consistency.
- Closes #

changed repeated word "checkout" to "check out" and removed full stops

---

src/app/users/(user-profile)/(components)/UserCommits.tsx
src/app/users/(user-profile)/[userId]/page.tsx

---
title: User Commits Fix - Corrected arguments
---
User Commits on the profile page was using the incorrect user arguments, this PR fixes that.
- closes #502

User Commits Fix - Corrected arguments

---

src/app/race/race.tsx

---
Fix Race results multiplayer
---
- Related Issue #487
- Closes #487

Fix race results multiplayer

---

src/app/race/(play)/multiplayer/page.tsx

---
---
- Related Issue #507
- Closes #507

Fix matchmaking logic

---

src/app/race/race.tsx
src/wss/game.ts
src/wss/schemas.ts

---
Race finish on all participants finish
---
Makes the race finish only when all participants of the race finish their typing
- Closes #

Race finish on all participants finish

---

src/config/achievements.ts

fixed misspelled badge image path

---

src/lib/logger.ts
src/scripts/setup.ts
src/scripts/tsconfig.json
tsconfig.json

---
title: Issue #439 | Cleanup / Refactor Setup Script
---
Discord Username: @connnnnnnorl
In my initial PR I added an additional tsconfig to get ts-node to work nicely with ESM. I figured out how to add ts-node overrides to the base tsconfig in this project which should help clean things up.
I also added the following:
1. A logger utility to nicely (with no third party deps) that log success, error, and warning messages.
2. A step for `npm install` since thats a critical step I missed in the initial PR.
Additionally, I forgot to add a step for installing dependencies which has been added in this PR.
- Related Issue #496

Cleanup Setup Script

---

src/app/race/(play)/multiplayer/page.tsx

---
Refactor: /race/(play)/multiplayer/page.tsx |
---
-remove dead code

Refactor: /race/(play)/multiplayer/page.tsx

---

src/app/race/_components/lobby-user.tsx
src/app/race/_components/multiplayer-loading-lobby.tsx
src/app/race/race.tsx

---
title: Issue #486 Update UI for the multiplayer race loading states
---
Discord Username: @snail
Updated the multiplayer race loading UI. 
Loading UI if a user is logged in:
https://github.com/webdevcody/code-racer/assets/52484866/77463d15-c8a7-44ff-9dc8-188cf3a804d1
Loading UI if user is not logged in (guest):
Loading race results UI:
- Related Issue #486 
- Closes #486

#486 Update UI for the multiplayer race loading states

---

packages/app/src/app/race/_components/race/race-multiplayer.tsx
packages/app/src/app/result/page.tsx
packages/wss/src/events.ts
packages/wss/src/game.ts
packages/wss/src/schemas.ts

---
title: Issue # | Avoid using event string literal
---
- Closes #

Chore: Avoid using event string literal

---

packages/app/src/app/race/_components/race/race-multiplayer.tsx
packages/app/src/lib/prisma.ts
packages/wss/src/events.ts
packages/wss/src/exceptions.ts
packages/wss/src/game.ts

---
Remove exceptions in WSS
---
- Related Issue #519
- Closes #519

Removed exceptions from wss

---

packages/app/.eslintrc.json
packages/wss/src/types.ts

---
Fix eslint project path
---
- Closes #

Fix eslint project path

---

packages/app/src/app/race/(play)/multiplayer/page.tsx
packages/app/src/app/race/(play)/practice/page.tsx
packages/app/src/app/race/_components/race/buttons/report-button.tsx
packages/app/src/app/race/_components/race/buttons/restart-button.tsx
packages/app/src/app/race/_components/race/footer.tsx
packages/app/src/app/race/_components/race/header.tsx
packages/app/src/app/race/_components/race/line-numbers.tsx
packages/app/src/app/race/_components/race/race-multiplayer.tsx
packages/app/src/app/race/_components/race/race-practice.tsx
packages/app/src/app/race/_components/race/types.d.ts
packages/app/src/app/race/_components/race/utils.ts

---
Refactor: /race |
---
The purpose of this pull request is to create a starting point to decouple the logic of practice / multiplayer / friends races instead of trying to incorporate the seperate logic into one file. 
This way we are not loading unused logic into pages or connecting to the server for the practice race.
And, when editing the logic for a specific game setting it will not affect the logic for the seperate pages.
Practice race has been decoupled from multiplayer race. The multiplayer race can now be edited without having to incorporate the practice race.
-create race components: Header, Footer,  LineNumbers, RestartButton 
-relocate buttons to /_components/buttons
-remove multiplayer logic from practice race …

Refactor: /race

---

CONTRIBUTING.md
packages/app/src/app/race/_components/cards/multiplayer-race-card.tsx
packages/app/src/app/race/_components/cards/practice-race-card.tsx

---
title: Issue # | Select input being yellow and update CONTRIBUTING.md 
---
Discord Username: @ysl0212
The input select being yellow, should be ghost.
- Closes #

Fixed select input being yellow and CONTRIBUTING.md update

---

packages/app/src/app/contributors/page.tsx

---
---
Discord Username: @sina-salahshour
added max page limit in the `contributors` page. right now, the `next page` button doesnt's stop and increase current page value in any case.
limited that to maximum possible page count.
changed minimum possible page to a Math.min, instead of ternary check.
- Closes #

fix(contributors): add page limit to pagination

---

packages/app/src/app/result/replay-timestamps.tsx

---
title: fix: replay buttons positioning and cursor type
---
Discord Username: @xross1430
- [x ] 🍕 Feature
- [ x] 🐛 Bug Fix
Replay buttons were positioned underneath the text and the cursor wouldn't change to a pointer when hovering over them.

fix: replay buttons positioning and cursor type

---

packages/app/src/app/result/page.tsx

---
title: #536 improve bottom spacing for results page
---
Discord Username: @abdelmuttalib1
- [ x] 🍕 Feature
- [ x] 🐛 Bug Fix
This is a UI issue in the results page where the results page doesn't have a bottom spacing that separates it and gives room for the results actions to be scrollable and easy to see especially when the code block size is taking more height then the actions below it will be kinda hard to see especially that it will be so close to the page footer, image below shows this UI issue.
issue:
fix:
issue:
fix:
this change is an update in terms of UI and user experience, so it's related to accessibility but not a real accessibility concern that need additional processes as it is a spacing improvement
- [ x] 🙅 no, because they aren't needed

add bottom spacing for results page to improve UI and user experience

---

packages/app/src/app/contributors/page.tsx
packages/app/src/config/site.ts

---
title: Issue # | Change max per page, and change revalidation back to 1 hour
---
- Closes #

Fix caching issue (Hopefully)

---

packages/app/src/app/race/_components/race/race-multiplayer.tsx
packages/app/src/app/race/_components/race/race-practice.tsx
packages/app/src/app/race/_components/race/race-tracker.tsx
packages/app/src/components/ui/progress-bar.tsx

---
title: Issue # | 532
---
Progression bar was inaccurate due to using absolute values, using relative position % fixed it.
Also progression bar had too much delay for transition, i lowered it so you can still see visual transition but feel more responsive.
- Related Issue #532
- Closes #532
BEFORE: 
[Screencast from 07-26-2023 08:44:21 AM.webm](https://github.com/webdevcody/code-racer/assets/112876685/e7db01a9-7268-459c-9146-1784b883f36d)
AFTER:
[Screencast from 07-26-2023 08:54:20 AM.webm](https://github.com/webdevcody/code-racer/assets/112876685/1932e59f-9024-4134-82a2-650e984df97f)

#532  accurate progression bar

---

packages/app/src/app/dashboard/_components/recentRaces.tsx
packages/app/src/app/dashboard/races/loaders.ts

---
title: Feature | Include Snippet's Language in the Recent Races Table
---
Discord Username: @Amenofisch
- [X ] 🍕 Feature
This PR adds a new column to the Recent Races Table found under the user's dashboard
- Closes #
1. Complete a race
2. Go to your dashboard and click on "profile", you should see a new column named "Language"
None atm
Just a new column in the dashboard -> recent races
- [X ] 🙅 no, because they aren't needed

include snippet language in recent races table

---

packages/app/src/app/result/page.tsx

---
title: Issue #538 improve bottom spacing for results page
---
Discord Username: @abdelmuttalib1
- [x ] 🍕 Feature
- [x ] 🐛 Bug Fix
This PR was merged earlier but changes were only applied to authenticated results page, this commit adds the spacing to unauthenticated results page as well so same changes.
Merged PR https://github.com/webdevcody/code-racer/pull/538
- [ x] 🙅 no, because they aren't needed

add results page bottom spacing for unauthenticated page

---

packages/app/src/app/contributors/_components/additions-deletions.tsx
packages/app/src/app/contributors/_components/contributor.tsx
packages/app/src/app/contributors/_components/github-commit-display.tsx
packages/app/src/app/contributors/_helpers/types.ts
packages/app/src/app/contributors/_helpers/utils.ts
packages/app/src/app/contributors/page.tsx

---
title: Issue # | Chore: Refactored Contributors Page
---
- Extensive rafactor
- Closes #

Chore: Refactored Contributors Page

---

README.md

---
---
Discord Username: robodad
Markdown formatting fix to acknowledgements section.
n/a
n/a
n/a
- [x ] 🙅 no, because they aren't needed

Fix acknowledgements formatting

---

.github/workflows/main.yml
packages/app/package.json
packages/app/prisma/seed-data/snippets.ts
packages/app/tailwind.config.js

---
Fix: Project Does Not Build - High Priority #561
---
-revert tailwind config
- Closes #561

Fix: Project Does Not Build - High Priority #561

---

packages/app/cypress/e2e/TestContributerPage.cy.js

---
title: Issue # | Adding Back Contributors Page E2E test
---
- Closes #

Adding Back Contributors Page E2E test

---

packages/app/src/app/race/_components/race/race-multiplayer.tsx
packages/app/src/app/race/actions.ts
packages/wss/src/game.ts

---
title: Issue #570
---
Connect a Result record to a RaceParticipant
- Use the raceStatus enum object instead of using literal strings on race status in game.ts
- Related Issue #570
- Closes #570

[#570] Save race participant result

---

packages/app/src/app/dashboard/_components/achievementProgress.tsx
packages/app/tailwind.config.js

---
title: Issue # | [BUG]: Fixed Tailwind.config 
---
I changed the animation.
- Closes #

Fix build fail

---

packages/app/src/app/race/_components/race/race-multiplayer.tsx
packages/app/src/app/race/_components/race/race-tracker-mutliplayer.tsx
packages/app/src/app/race/_components/race/race-tracker.tsx
packages/app/src/app/race/actions.ts
packages/wss/src/game.ts

---
Fixes a bug on the race result action on practice mode
---
- Also fixes a bug in the race tracker on multiplayer races
- Related Issue #582
- Closes #582

Fix result action error on practice mode

---

CONTRIBUTING.md
package.json

---
title: Issue #563  | Update CONTRIBUTING.md doc
---
Added a run script to top level package.json
```json
"pr:precheck": "npm run lint -w @code-racer/app && npm run type-check -w @code-racer/app && npm run build -w @code-racer/app"
```
- Related Issue #563 
- Closes #563

[563] Update CONTRIBUTING.md doc

---

packages/app/src/app/about/page.tsx

---
title: Issue # | About Page content
---
added first edition content for the about page
Discord Username: @BlakeLawrence 
- Related Issue #546 
- Closes #546 
used lighthouse to test accessibility

About font

---

.github/workflows/main.yml
packages/app/package.json

---
title: Issue # | Refactor Workflow to use Cypress Official GitHub Actions
---
- Closes #

Refactor Workflow to use Cypress Official GitHub Actions

---

CONTRIBUTING.md

---
---
A capitalization and simple formatting. Just to get started on my open-source contribution.
Discord Username: @Wertyp
A capitalization and simple formatting. Just to get started on my open-source contribution.
- Closes #

updating the docs so it looks a bit nice

---

packages/app/src/components/data-table/data-table-view-options.tsx
packages/app/src/lib/utils.ts

---
title: Issue #573 | Add method to convert camel case to titlecase
--
Discord Username: @saga_sanga
On the leaderboards page, the table's view button's toggle options have some options that are written in camel case. I've added a method called `camelCaseToCapitalized` to the `app/lib/utils.ts` file to convert camelCase to Title Case.
Before:
After:
- Related Issue #573
- Closes #573

[#573] Feat: Add method to convert camel case to titlecase

---

packages/app/cypress/e2e/TestPracticeRace.cy.js
packages/app/src/app/add-snippet/_components/language-dropdown.tsx
packages/app/src/app/race/_components/cards/practice-race-card.tsx

---
title: Issue # | Added Practice Race Page E2E test
---
This E2E test user flow from navigating from home page to finishing the race
- Closes #
https://github.com/webdevcody/code-racer/assets/57098413/e9c0cc56-1bb7-4211-8d63-9b26718da671
POV: You're testing e2e on your ancient laptop

Added Practice Race Page E2E test

---

packages/app/src/app/contributors/page.tsx

---
title: Issue # | Pagination controls added to bottom of screen
---
Discord Username: @BlakeLawrence 
added a copy of the pagination-bar to bottom of screen within a centered div
- Related Issue #584 
- Closes #584

added pagination controls to bottom of page

---

packages/app/src/app/contributors/_components/contributor.tsx
packages/app/src/app/contributors/_components/github-commit-display.tsx

---
title: Issue # | 545
---
Clicking contributor profile or contributor commits now opens in new tab.
- Related Issue #545
- Closes #545

#545 | open contributor in new tab

---

packages/app/cypress.config.ts
packages/app/cypress/e2e/TestContributerPage.cy.js
packages/app/cypress/e2e/TestPracticeRace.cy.js
packages/app/src/app/contributors/_components/contributor.tsx
packages/app/src/app/contributors/_components/github-commit-display.tsx
packages/app/src/app/race/_components/race/race-practice.tsx

---
title: Issue # | Implement Cypress Best Practices
---
Following Cypress Best Practices
- Test query command is now de-coupled from ui specific element (use `data-*` attribute selector instead)
- Changed Cypress scrolling behavior `scrollBehavior: "center"`
- Added `baseUrl` in Cypress config
- Closes #

Implement Cypress Best Practices

---

.github/workflows/main.yml

turn off cypress taking screenshots

---

package-lock.json
packages/app/package.json
packages/app/src/app/race/_components/race/footer.tsx
packages/app/src/app/race/_components/race/race-multiplayer.tsx
packages/app/src/app/race/_components/race/race-timer.tsx

---
title: Issue #587 | Fixing the strange timer behaviour
---
Discord Username: @kozie
This PR fixes the timer issues including:
- stops the timer when finishing the race
- shows the counts in seconds (not milliseconds)
- removes "pretty-ms" package because we don't need it anymore
- Related Issue #587
Before:
After:

[#587] Strange timer behaviour

---

README.md

---
Updating docs and fixing a broken link
---
- Closes #

Updating docs and fixing a broken link

---

packages/app/src/app/dashboard/_components/snippetsTable.tsx

---
title: Issue #554 
---
Discord Username: @industrializeddark
Updated snippet language column to use snippet labels from config file.
- Related Issue #554 
- Closes #554

Updated language column to use same label as in recent races page

---

packages/app/src/app/contributors/_components/pagination-bar.tsx
packages/app/src/app/contributors/page.tsx

---
title: Issue # | Added page number to the contributing page
---
Discord Username: @idk23535
Added page number to the contributing page!
- Closes #

added page number to the contributing page.

---

packages/app/src/app/dashboard/_components/achievementProgress.tsx
packages/app/src/app/dashboard/timeline.css

---
title: Issue #580 
---
Discord Username: @industrializeddark
- Related Issue #580 
- Closes #580

Profile Page awards jitter and stutter when hovered

---

packages/app/prisma/schema.prisma
packages/app/src/app/leaderboard/users-table.tsx
packages/app/src/app/race/actions.ts

---
title: Issue #568 | Adding Top languages field in Leader board
---
Added 'Top languages' field in leader boards
Schema update and Action update for race
Discord Username: @.d_k5g_1am_go.
- [✅] 🍕 Feature
**Motivation:** Avg CPM, Accuracy and Races Played are good rank measures but doing only python races compared to java race is very different, so adding top languages field will help for better performance measure.
**Summary:**
Added 'Top languages' field in leader boards.  
For adding/implementing the feature:
1. Database had to be updated. Database update -> Added languagesMap and topLangauges field in User model.
2. I have updated **_saveUserResultAction_** to update the _langauageMap_ and _topLanguages_ User fields whenever user completes a race.
- Related Issue #568 
- Closes #568 …

#568 Adding Top languages field in Leader board

---

packages/app/src/app/contributors/_components/additions-deletions.tsx
packages/app/src/app/contributors/_components/contributor.tsx
packages/app/src/app/contributors/page.tsx
packages/app/src/components/ui/card.tsx

---
---
Discord Username: @awfu1minded
Added some UI improvements to contributors page that looks better imo
- Closes #

Contributors page UI improvements

---

packages/app/src/app/race/(play)/practice/page.tsx
packages/app/src/app/race/_components/race/code.tsx
packages/app/src/app/race/_components/race/race-multiplayer.tsx
packages/app/src/app/race/_components/race/race-practice.tsx
packages/app/src/app/race/_components/race/types.d.ts
packages/app/src/app/result/chart.tsx
packages/app/src/app/result/replay-timestamps.tsx
packages/app/src/types/result.ts

---
Fix: Replay Highlighting
---
-decouple code highlighting
-rename types
-remove dead code
-refactor
Includes some refactoring that covers multiple files.

Fix: Replay Highlighting

---

packages/app/src/app/page.tsx

---
title: Issue # | Fix GitHub Star not showing up on home page
---
Fix fetch to get repo github star failed (401 status code) due to incorrect request headers
- Closes #

Fix GitHub Star not showing up on home page

---

packages/app/cypress/e2e/page-objects/components/NavbarComponent.ts
packages/app/cypress/e2e/page-objects/pages/LeaderboardPage.ts
packages/app/cypress/e2e/page-objects/pages/index.ts
packages/app/cypress/e2e/tests/TestLeaderboard.cy.js

---
title: Issue #619 | I have added leaderboard tests and commented out the locally not working code
---
Discord Username: @wirblewind._.
I have created a leaderboard test that navigates to the leaderboard, selects the row-dropdown and validates if it is selected as expected. I wanted to add validations of the user-rows, but that is not locally possible, as it doesn't show me any users there. Maybe we could fill in some dummy data or use the actual data if possible, but for now i have left all the things related to this commented out for later use (So its possible that the commented code doesn't work 100%).
- Related Issue #619
- Closes #

added leaderboard tests

---

packages/app/prisma/schema.prisma
packages/app/src/app/race/(play)/practice/page.tsx
packages/app/src/app/review/_components/review-buttons.tsx
packages/app/src/app/review/actions.ts
packages/app/src/components/header.tsx
packages/app/src/components/icons.tsx
packages/app/src/components/notification-item.tsx
packages/app/src/components/notification.tsx
packages/app/src/lib/notification.ts

---
title: Issue # | Notification System
---
Primitive notification system. for now user will receive a notification if reported snippet has been acquitted, updated, or deleted.
we can push a notification to a user by calling `pushNotification` in src/lib/notification.ts
- Related Issue #621 
- Closes #
https://www.youtube.com/watch?v=gCGxGC0KIHc

[621] feat: Notification System

---

packages/app/cypress/e2e/tests/TestPracticeRace.cy.js

---
title: Issue #630 |
---
Discord Username: @wirblewind._.
I have added shoulds on a some points of the practice race test. Explanation, can be seen in the ticket #630
- Related Issue #630
- Closes #630

added shoulds to practice race test

---

packages/app/src/app/race/_components/race/race-multiplayer.tsx
packages/app/src/app/race/_components/race/race-practice.tsx
packages/app/src/app/race/_components/race/utils.ts
packages/app/src/app/result/result-chart.tsx

---
Fix: Result Chart
---
-removed Android code from practice race 
-created Android branch to store the Android code.; asked the creator to create branch to store the Android code; 
-practice race will set correct timestamps
-utils functions will return 0 instead of NaN
-result chart will graph data correctly
-remove useEffect from result chart
-add / remove result chart types
-refactor multiplayer race to reflect chart changes to practice race
-multiplayer race will set correct timestamps
- Closes #626
- Closes #622
Android code created additional issues other than affecting the result graph.
<strike> Multiplayer race will need to be refactored to reflect practice race. </strike>

Fix: Result Chart

---

packages/app/prisma/seed-data/users.seed.ts
packages/app/prisma/seed.ts

---
[TASK]: Create seed for local script [E2E] #624
---
Discord Username: @chris_
- [x ] 🍕 Feature
I was addressing the following task: https://github.com/webdevcody/code-racer/issues/624
What I did was create a TypeScript file with test data that includes random values for average accuracy and average CPM. Afterwards, I extended the seed.ts script to generate the test data locally, allowing others to test on the leaderboard as well. Additionally, I added a FIFTH_RACE achievement for each account to ensure their presence on the leaderboard.
- Related Issue https://github.com/webdevcody/code-racer/issues/624
- Closes https://github.com/webdevcody/code-racer/issues/624
There are no instructions as this script automatically runs when you run the application locally. 
No, I only added test …

Created seed for local script to test leaderboard

---

package-lock.json
packages/app/package.json
packages/app/src/app/add-snippet/_components/actions.ts
packages/app/src/app/add-snippet/_components/add-snippet-form.tsx
packages/app/src/config/site.ts

---
title: Issue # | Format Snippet using Prettier API
---
Currently Prettier only support: Go, Java, Javascript, Typescript, Ruby, HTML
When user submit a snippet, it only format snippet if snippet's language is supported. Since Prettier parse code into Abstract Syntax Tree first before apply formatting, we get benefit of syntax validation as a bonus.
- Related Issue #644
- Closes #644 
Submitting a badly formatted snippet
https://github.com/webdevcody/code-racer/assets/57098413/c3f35bbb-8b24-4c08-8099-95084117646c
Submitting syntax error snippet
https://github.com/webdevcody/code-racer/assets/57098413/9613c6aa-c785-4d77-8877-618f2e9237c6

[644] feat: Format Snippet using Prettier API

---

packages/app/src/config/site.ts

---
title: Issue # | Temporary disable Go lang prettier plugin
---
- Closes #

Temporary disable Go lang prettier plugin due to some issue

---

packages/app/src/config/site.ts

---
title: Issue # | Temporary remove plugins options from prettier config
---
- Closes #

Temporary remove plugins options from prettier config

---

packages/app/src/config/site.ts

---
title: Issue # | Potential fix for prettier module not found error
---
- Closes #

Potential fix for prettier module not found error

---

packages/app/src/lib/socket.ts

fix: change socket connection url

---

packages/app/src/app/race/_components/race/game-multiplayer.tsx
packages/app/src/app/race/_components/race/header.tsx

---
---
fixed where the snippet name would always say "Type Snippet null"
- Closes #

Fixing snippet name

---

packages/app/src/app/users/(user-profile)/(components)/UserCommits.tsx
packages/app/src/app/users/(user-profile)/(components)/actions.ts
packages/app/src/app/users/(user-profile)/(components)/delete-confirmation.tsx
packages/app/src/app/users/(user-profile)/(components)/profile-card.tsx
packages/app/src/app/users/(user-profile)/(components)/reset-confirmation.tsx
packages/app/src/components/main-nav.tsx
packages/app/src/components/mobile-nav.tsx
packages/app/src/components/user-dropdown.tsx

---
[BUG] #668 | Fixed username overflow issue
---
Discord Username: @quickermaths
Fixed username overflowing in delete and reset modals as well as in main and mobile nav, added character limit (39 as is also Github username limit) in updating username functionality. 
Besides this also solved the issue of closing mobile nav while navigating to user profile or dashboard from user dropdown menu.
- Closes #668

#668 Fixed username overflow issue

---

packages/app/src/app/dashboard/_components/recentRaces.tsx

---
title: Issue # | fixed snippet name
---
Discord Username: @idk23535
- Closes #

fixed the snippet name on the dashboard

---

CONTRIBUTING.md
README.md

---
title: Issue # Youtube videos update and some small additions
---
- Closes #

Youtube videos update and some small additions

---

CONTRIBUTING.md

adding a 'make sure' step in the installation section

---

packages/app/cypress/e2e/page-objects/pages/RacePage.ts
packages/app/cypress/e2e/tests/TestPracticeRace.cy.js

---
---
- Closes #
- [*] 👍 yes

cypress test fix

---

CONTRIBUTING.md

---
title: Issue # | fix db error when setting up docker first time
---
There's a bug in docker while installing on Mac m1, this fix will give contributors a fix in case they face the error.  
- Closes #

add step to fix docker error

---

README.md

---
title: Issue #686  |
---
- [ Y] 📝 Documentation Update
Update Icons in Readme
- Closes #
- [Y ] 🙅 no, because they aren't needed

#686 | Update README.md Icons

---

.gitignore
README.md
packages/app/src/app/add-snippet/_components/language-dropdown.tsx
packages/app/src/app/contributors/_components/github-commit-display.tsx
packages/app/src/app/contributors/page.tsx
packages/app/src/app/dashboard/_components/snippetsTable.tsx
packages/app/src/app/leaderboard/sort-filters.ts
packages/app/src/app/leaderboard/user-rankings.tsx
packages/app/src/app/leaderboard/users-table.tsx
packages/app/src/app/privacy/page.tsx
packages/app/src/app/race/(play)/multiplayer/room.tsx
packages/app/src/app/race/(rooms)/[roomId]/page.tsx
packages/app/src/app/race/(rooms)/[roomId]/room.tsx
packages/app/src/lib/validatedCallback.ts

---
title: Issue #693  | Updated contributor count per page to look connected and avoid empty spaces for all the screens. Also removed the unused imports from few files for better maintainability. And Fixed the ReadMe  MD warnings.
---
Solve this - 
Discord Username: @ vignesh-gupta
- Related Issue #693 
- Closes #693 
NO Impact on Accessibility.

[Updated] Contributor Count per page

---

README.md
packages/app/cypress/e2e/page-objects/pages/RacePage.ts
packages/app/cypress/e2e/tests/TestPracticeRace.cy.js

---
title: Issue # | Fixed Failing Practice test + Added Dynamic badges to readme 
---
Discord Username: @ vignesh-gupta
- Related Issue #697
- Closes #686 #697

Fixed Failing test + Added badges 

---

package-lock.json
packages/app/package.json
packages/app/src/app/race/_components/create-room-form.tsx
packages/app/src/lib/validations/room.ts
packages/wss/package.json
packages/wss/src/events/client-to-server.ts
packages/wss/src/game.ts

---
---
move generating roomId to wss server so it wont be cached
- Closes #

fix: move generating roomId to wss server

---

CONTRIBUTING.md

updating docs in caps

---

README.md

---
title: Add new youtube live stream from Cody
---
- Closes #

Add missing youtube live stream from Cody

---

packages/app/src/app/users/(user-profile)/(components)/profile-card.tsx

---
title: Issue #724 | Removed Mandatory * for Biography
---
Discord Username: @bmonish
- Related Issue #724 
- Closes #724

[724] | Removed Mandatory * for Biography

---

CONTRIBUTING.md

Fix indentation in Step 10 of Project Documentation

---

CONTRIBUTING.md

updating the docs to make easier to understand

---

CONTRIBUTING.md

add new proposal as docs

---

package-lock.json
package.json

Update package.json file add prisma and @prisma/client

---

package-lock.json
packages/app/prisma/schema.prisma
packages/app/src/app/dashboard/_components/recentRaces.tsx

---
---
- [ X] 🐛 Bug Fix
- Closes #
- [X ] 🙅 no, because they aren't needed

Bug with recent races table in dashboard

---

CONTRIBUTING.md

---
[#753] | Update documentation
---
Discord Username: @yaq0ub
Indent step 10 in documentation
- Related Issue # #753
- Closes # #753

indent step 10 in documentation
